### ISSUE TITLE
error with gmail configuration

### ISSUE THREAD

**Issue by jagdishjadeja** [squareboat/nest-mailman#12]
I have set my gmail account configuration in mailman as following 
```
MailmanModule.register({
      host: 'smtp.gmail.com',
      port: 25,
      username: 'username@customdomain.com',
      password: `****`,
      from: 'username@customdomain.com',
    }),
```
and facing error

``` 
Error: connect ETIMEDOUT 74.125.200.108:25
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1128:16) {
  errno: -4039,
  code: 'ESOCKET',
  syscall: 'connect',
  address: '74.125.200.108',
  port: 25,
  command: 'CONN'
}
```

**Comment by vinayak25** [comment]
Hi @jagdishjadeja, did you check the configuration for your gmail's smtp server? The error usually occurs when mailman tried to connect with server, but it doesn't exist. For example, gmails smtp server runs on 465 or 587. You can find more details at https://www.hostinger.in/tutorials/how-to-use-free-google-smtp-server

**Comment by tanmaymohan** [comment]
Port 25 is usually blocked due to spam/security reasons on most of the firewalls, please check with the above-mentioned ports

**Comment by sb-vinayak** [comment]
Closing it due to inactivity.

**Comment by vinayak25** [comment]
Closing it due to inactivity.
