### ISSUE TITLE
discord link is broken

### ISSUE THREAD

**Issue by jagdishjadeja** [squareboat/nest-mailman#13]
discord link on website is not working

**Comment by tanmaymohan** [comment]
Hello @jagdishjadeja  

It seems that the link got expired really quickly due to misconfigured settings.

Here is an updated link from where you can join in : [https://discord.com/invite/mB8wx86fns](url)

**Comment by tanmaymohan** [comment]
Meanwhile, I am updating the documentation for the same

**Comment by vinayak25** [comment]
Closing it due to inactivity.
