### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by BobSarfo** [squareboat/nest-mailman#16]
npm WARN deprecated highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest
npm WARN deprecated gulp-header@1.8.12: Removed event-stream from gulp-header
css-what: vulnerabilities,  Denial of Service

**Comment by SocketSomeone** [comment]
Any news here?

**Comment by vinayak25** [comment]
This is solved.
