### ISSUE TITLE
Missing JSX

### ISSUE THREAD

**Issue by johannesschobel** [squareboat/nest-mailman#30]
Just leaving this here, if someone stumbles upon the same issue..

I got the error message, that `JSX` namespace is not found.

the solution to this issue is as follows:

```
npm install --save-dev @types/react
```

**Comment by johannesschobel** [comment]
maybe you guys could add this to the `installation` step in the docs?

**Comment by vinayak25** [comment]
Hello @johannesschobel Thanks for reporting this issue! It has been resolved.
